name: "alpha"

on: "push"

jobs:
    alpha:
         runs-on: "ubuntu-latest"
         steps:
            - name: "Alarm"
              run: echo "hello world"

            - name: "completed greet"
              run: echo "task successfully completed"